### ISSUE TITLE
Scaling of do_ftemp_kphio for C4 plants

### ISSUE THREAD

**Issue by davidorme** [computationales/rpmodel#19]
The values used here:

https://github.com/computationales/rpmodel/blob/master/R/subroutines.R#L358

```r
ftemp = -0.008 + 0.00375 * tc - 0.58e-4 * tc^2
```

are incorrect. Shirley has pointed out that the values have been scaled twice in error and that these should be:

```r
ftemp = -0.064 + 0.03 * tc - 0.000464 * tc^2 
```

**Comment by stineb** [comment]
Thanks. I implemented this corrected parametrisation with commit d9177eec9bda55706c6133bb376b919a290cd19a.
